pipeline {
    agent any

    tools {
        maven 'Maven3'     // Jenkins Global Tools
        jdk 'JDK17'
    }

    environment {
        AWS_REGION = "ap-south-1"
        ACCOUNT_ID = "426315020355"
        ECR_REPO   = "securevault"

        IMAGE_TAG  = "${BUILD_NUMBER}"
        IMAGE_URI  = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"

        EC2_HOST   = "ubuntu@13.233.32.204"

        REQUIRED_SPRING_VERSION = "3.4.1"
        REQUIRED_JAVA_VERSION   = "17"
        ENV_FILE = ".env"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Validate Versions') {
            steps {
                script {
                    echo "Checking Spring Boot version..."
                    def springVersion = sh(
                        script: "grep -m1 '<version>' secure_vault_ai/pom.xml | head -1 | sed -E 's/.*<version>(.*)<\\/version>.*/\\1/'",
                        returnStdout: true
                    ).trim()
                    if (springVersion != REQUIRED_SPRING_VERSION) {
                        error "❌ Spring Boot version mismatch. Found: ${springVersion}, Required: ${REQUIRED_SPRING_VERSION}"
                    }
                    echo "✅ Spring Boot version OK: ${springVersion}"

                    echo "Checking Java version..."
                    def javaVersion = sh(
                        script: "java -version 2>&1 | head -n 1",
                        returnStdout: true
                    ).trim()
                    if (!javaVersion.contains(REQUIRED_JAVA_VERSION)) {
                        error "❌ Java version mismatch. Required Java ${REQUIRED_JAVA_VERSION}"
                    }
                    echo "✅ ${javaVersion}"
                }
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | \
                        docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build --platform linux/amd64 -t ${IMAGE_URI} .
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${IMAGE_URI}"
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    withCredentials([
                        string(credentialsId: 'POSTGRES_PASSWORD', variable: 'PG_PASS'),
                        string(credentialsId: 'MONGO_PASSWORD', variable: 'MONGO_PASS')
                    ]) {
                        sh """
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} '
                            aws ecr get-login-password --region ${AWS_REGION} | \
                            docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com &&

                            docker stop securevault || true &&
                            docker rm securevault || true &&

                            docker pull ${IMAGE_URI} &&

                            docker run -d \
                              --name securevault \
                              --env-file ${ENV_FILE} \
                              -e SPRING_DATASOURCE_PASSWORD=$PG_PASS \
                              -e SPRING_DATA_MONGODB_URI="mongodb+srv://flaman:$MONGO_PASS@securevaultai.mx0qhvx.mongodb.net?retryWrites=true&w=majority" \
                              -p 8080:4000 \
                              ${IMAGE_URI}
                        '
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}
